name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      parameter:
        description: Dummy parameter

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make API key file for pinecone DB
        run: echo API_KEY="${{ secrets.PINECONE_API_KEY }}" > ./.env.local

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_TAG }}:latest

      - name: Push the Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_TAG }}:latest

      - name: Copy API key file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: ".env.local"
          target: "/home/ubuntu/"

  ec2-pull:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Restart the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu
            sudo docker stop ai-server
            sudo docker rm ai-server
            sudo docker pull ${{ secrets.DOCKER_TAG }}:latest
            sudo docker create \
              --name ai-server \
              --volume /home/ubuntu/model:/workspace/model \
              -p 3000:3000 \
              ${{ secrets.DOCKER_TAG }}:latest
            sudo docker cp "/home/ubuntu/.env.local" ai-server:/workspace/
            sudo docker start ai-server
